### ISSUE TITLE
setUserId incorrect method name in iOS

### ISSUE THREAD

**Issue by Paul-Todd** [fullstackreact/react-native-firestack#194]
When calling setUser in analytics in iOS this references the native side method as "setUserId" instead of "setUser". If you attempt to call setUser in javascript this will reject the promise with an error.

This is in file react-native-firestack/lib/modules/analytics.js:34

Currently is:
  setUser(id, properties={}) {
    return promisify('**setUserId**', FirestackAnalytics)(id, properties);
  }

Should be:
  setUser(id, properties={}) {
    return promisify('**setUser**', FirestackAnalytics)(id, properties);
  }

**Comment by Salakar** [comment]
@Paul-Todd thanks for this 👍  this has been fixed in the upcoming v3 release of firestack - feel free to check out the v3 branch and use it directly, its stable.

A lot of the missing analytics methods have also been added as well as android support. Just note that v3 now heavily mirrors the firebase web sdk.

See [here](https://github.com/Salakar/react-native-firestack/blob/master/lib/modules/analytics.js) for the available methods.

Closing.
