### ISSUE TITLE
_clearer is not a function.

### ISSUE THREAD

**Issue by arunshan** [fullstackreact/react-native-firestack#199]
Hi Guys, Currently I am using the latest version of firestack in my project. 

Error: 

```
clearer is not a function. (In '_clearer(id)', '_clearer' is undefined)
2016-12-26 13:39:48.954 [fatal]
```

The following is the screencap of the error when I click on the facebook sign in button.

https://cl.ly/2E2h2l1X1T2V

Any help here is greatly appreciated. 

Thank You!

**Comment by alexkendall** [comment]
Use master now. The error is fixed there but a new release would be appreciated.

**Comment by Salakar** [comment]
@arunshan @alexkendall check out the v3 branch, that's the cutting edge release, now mirrors firebase web api, much more stable and error free as well as lots of missing features added.

Hope to have a release for it soon ™️ 

If you'd like a release for it now, like an alpha or something rather than using git then let @auser know =] he can release an alpha on npm.

Closing as issue fixed in upcoming version.

**Comment by auser** [comment]
👍 I'll pull this tomorrow (almost tomorrow already?) and update FirestackApp to go along with the new version.
