### ISSUE TITLE
[v3] .once gives error "FirestackDatabase.onOnce got 4 arguments, expected 5"

### ISSUE THREAD

**Issue by DaBs** [fullstackreact/react-native-firestack#220]
As title states. It seems to be pretty simple, just somebody who forgot to add the callback [here](https://github.com/fullstackreact/react-native-firestack/blob/v3/lib/modules/database/reference.js#L111). I haven't tested the fix, but will do in the near future.

**Comment by auser** [comment]
Yes, this is a hanging bug that's actually preventing the update to v3. @Salakar @chrisbianca

**Comment by chrisbianca** [comment]
@DaBs .promisify() adds the callback handler [here](https://github.com/fullstackreact/react-native-firestack/blob/v3/lib/utils/index.js#L135), so it doesn't need to be passed through where you've suggested.

@auser I'm using .once() without any issues, and can't figure out why this issue is affecting you both.  I'll ping you on chat and see whether we can get to the bottom of this.

**Comment by moooji** [comment]
Looks like for some reason `args[3]` (eventName) is `undefined`.

**Comment by moooji** [comment]
@DaBs The (reference.js) code you are linking to is actually not being used :-o The actual implementation seems to be here https://github.com/fullstackreact/react-native-firestack/blob/v3/lib/modules/database.js#L222

And there seems to be the `modifiersString` argument missing.

**Comment by Salakar** [comment]
@moooji that explains that, that'll be @auser who did that merge then ;p was all good at my last merge and there should be any direct merges except from my remote branch, otherwise it screws up like this.

@auser https://github.com/fullstackreact/react-native-firestack/commit/3612e8259647b5058d4087918ed8be87038c9291

@Ehesp

**Comment by Salakar** [comment]
@moooji use my fork, that's all correct there with no weird merges.

**Comment by DaBs** [comment]
Closing this as it's no longer relevant as the v3 branch of @Salakar is obviously working.
