### ISSUE TITLE
Firestack init called twice

### ISSUE THREAD

**Issue by chaitanya0bhagvan** [fullstackreact/react-native-firestack#98]
Logs in XCode show _Setting up Firestace instance_ twice. So Firestack is created twice and the first object is destroyed soon after. I am not able to figure out where this creation is happening.

**Comment by auser** [comment]
Ah... yes, this was a lower priority for me... originally, this was addressed by hooking into the `AppDelegate`... since I pulled away from that (to support swift support), this was introduced. In part, this happens because the `configure()` method happens after React Native creates the Firestack instance initially. Since it's mostly benign, I've pushed this priority lower.
